budget/urls.py
from django.urls import path, include

from budget.views import EditInkomstView, IdagsView, IdagsnyainkomstenVIew, IdagsnyautgiftenVIew



app_name='budget'
urlpatterns=[
    path('', IdagsView.as_view(),name='idag-view'),
    path('ny-inkomst-idag/', IdagsnyainkomstenVIew.as_view(),name='idag-nya-in'),
    path('ny-utgift-idag/', IdagsnyautgiftenVIew.as_view(),name='idag-nya-ut'),
    path('ut/<pk>/edit', EditInkomstView.as_view(),name='edit-in-idag'),
    path('in/<pk>/edit', EditInkomstView.as_view(),name='edit-ut-idag'),
    ]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import STATICFILES_DIRS
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('budget.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget/models.py
from operator import mod
from statistics import mode
from django.db import models
import datetime 
from datetime import timedelta

current_date = datetime.date.today()
datetime_tomorrow = current_date + timedelta(days=1)

class TheDay(models.Model):
    date=models.DateField( null=False, blank=False, unique=True, auto_now=False)
    totalInkomst=models.IntegerField(default=0, blank=True, null=True )
    totalUtgift=models.IntegerField(default=0, blank=True, null=True )
    
    def __str__(self) -> str:
        return str(self.date)
    
    def save(self, *args, **kwargs):
        day=int(current_date.day)
        month=int(current_date.month) * 100
        year=int(current_date.year)* 10000  
        try:
            if TheDay.objects.get(date=self.date).date == current_date:
                self.pk=year+month+day
            self.totalInkomst=0
            self.totalUtgift=0
            for item in DagligaUtgifter.objects.filter(the_day__date__contains=self.date):
                self.totalUtgift+= item.amount
            for item in DagligaInkomster.objects.filter(the_day__date__contains=self.date):
                self.totalInkomst+= item.amount
        except:
                pass
            

        return super(TheDay, self).save(*args, **kwargs)

       
class DagligaUtgifter(models.Model):
    name=models.CharField(max_length=100, blank=False, null=False)
    amount=models.IntegerField(default=0)
    the_day=models.ForeignKey(TheDay, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
    def __str__(self) -> str:
        return f"{self.the_day} | {self.name}"
    
class DagligaInkomster(models.Model):
    amount=models.IntegerField(default=0)
    the_day=models.ForeignKey(TheDay, on_delete=models.CASCADE)
    kommentar=models.TextField(blank=True, null=True)
    name=models.CharField(default="no", blank=False, null=False, max_length=150)
    klient=models.ForeignKey('Klient', on_delete=models.RESTRICT, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.the_day} | {self.amount}"


class Klient(models.Model):
    name=models.CharField(max_length=150, null=False, blank=False)

    def __str__(self):
        return self.name
    

budget/views.py
from asyncio.windows_events import NULL
import datetime
import json
from django.shortcuts import redirect, render
from django.views.generic import View,CreateView, UpdateView, TemplateView
from datetime import timedelta
from budget.models import DagligaInkomster, Klient, TheDay, DagligaUtgifter
current_date = datetime.date.today()
week = current_date + timedelta(days=-6)

day=int(current_date.day)
month=int(current_date.month) * 100
year=int(current_date.year)* 10000


class IdagsnyautgiftenVIew(CreateView):
    model=DagligaUtgifter
    fields=['amount', 'name']
    template_name="budget/idags-nya-utgift-view.html"

    def post(self, request):
        amount = request.POST['amount']
        name = request.POST['name']
        the_day = TheDay.objects.get(date=current_date)
        instance= DagligaUtgifter(name=name, amount=amount, the_day=the_day)
        instance.save()
        return redirect("budget:idag-nya-ut")

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            idag=TheDay.objects.get(date=current_date)
            context['idag']= idag
            if  idag.totalUtgift+idag.totalInkomst==0:
                context['perut']= int((idag.totalUtgift /(idag.totalUtgift+idag.totalInkomst))*100)
                context['perin']= int((idag.totalInkomst /(idag.totalUtgift+idag.totalInkomst))*100)
            else:
                context['perut']= int(100)
                context['perin']= int(100)
            context['utgifter'] = DagligaUtgifter.objects.filter(the_day__date=current_date).order_by('amount')
            context['inkomster'] = DagligaInkomster.objects.filter(the_day__date__contains=current_date)
            context['indata'] =json.dumps( [
                {
                    'id': obj.id,
                    'amount': obj.amount,
                    'date': current_date.strftime("%A"),
                }
                for obj in DagligaInkomster.objects.filter(the_day__date__contains=current_date)
            ])
            context['utdata'] = json.dumps([
                {
                    'id': obj.id,
                    'amount': obj.amount,
                    'name': obj.name
                }
                for obj in DagligaUtgifter.objects.filter(the_day__date=current_date)
            ])
            context['veckoutdata'] = json.dumps([
                {
                    'id': obj.id,
                    'totalUtgift': obj.totalUtgift,
                    'totalInkomst': obj.totalInkomst
                }
                for obj in TheDay.objects.filter(date__lte=current_date , date__gte=week)
            ])
            return context


class IdagsnyainkomstenVIew(CreateView):
    model=DagligaInkomster
    fields=['amount', 'klient', 'kommentar']
    template_name="budget/idags-nya-inkomst-view.html"

    def post(self, request):
        amount = request.POST['amount']
        kommentar = request.POST['kommentar']
        klient = request.POST['klient']
        the_day = TheDay.objects.get(date=current_date)

        instance=DagligaInkomster(kommentar=kommentar, amount=amount, the_day=the_day)

        try:
            obj = Klient.objects.get(name__iexact=klient)
        except Klient.DoesNotExist:
            obj = Klient(name=klient)
            obj.save()
        instance.klient=obj
        instance.save()

        return redirect("budget:idag-nya-in")

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)

        this_date=TheDay.objects.get(id=year+month+day)
        dags_inkomster=DagligaInkomster.objects.filter(the_day=this_date).order_by('klient')
        context['dags_inkomster']=dags_inkomster
        context["dags_utgifter"] = DagligaUtgifter.objects.filter(the_day=this_date).order_by('amount')
        return context

class IdagsView(TemplateView):
    template_name="budget/idag-template.html"
    def get(self, request, *args, **kwargs):
        
        if not TheDay.objects.filter(date=current_date).exists():
            instance=TheDay(date=current_date)
            instance.save()
            date=[]
            d=[]
            m=[]
            y=[]
            for x in range(7):

                date.append( current_date+ timedelta(days=-x-1))
                d.append(date[x-1].day)
                m.append(date[x-1].month)
                y.append(date[x-1].year)
                ins=TheDay(date=date[x-1], id=y[x-1]*10000+d[x-1]+m[x-1]*100)
                ins.save()
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        idag=TheDay.objects.get(date=current_date)
        context['idag']= idag
        if  idag.totalUtgift+idag.totalInkomst!=0:
            context['perut']= int((idag.totalUtgift /(idag.totalUtgift+idag.totalInkomst))*100)
            context['perin']= int((idag.totalInkomst /(idag.totalUtgift+idag.totalInkomst))*100)
        else:
            context['perut']= int(100)
            context['perin']= int(100)
            date=[]
            d=[]
            m=[]
            y=[]
        for x in range(7):
            date.append( current_date+ timedelta(days=-x-1))
            d.append(date[x-1].day)
            m.append(date[x-1].month)
            y.append(date[x-1].year)
        context['date']=date
        context['d']=d
        context['m']=m
        context['y']=y
        context['utgifter'] = DagligaUtgifter.objects.filter(the_day__date=current_date).order_by('amount')
        context['inkomster'] = DagligaInkomster.objects.filter(the_day__date__contains=current_date)
        context['indata'] =json.dumps( [
            {
                'id': obj.id,
                'amount': obj.amount,
                'date': current_date.strftime("%A"),
            }
            for obj in DagligaInkomster.objects.filter(the_day__date__contains=current_date)
        ])
        context['utdata'] = json.dumps([
            {
                'id': obj.id,
                'amount': obj.amount,
                'name': obj.name
            }
            for obj in DagligaUtgifter.objects.filter(the_day__date=current_date)
        ])
        context['veckoutdata'] = json.dumps([
            {
                'id': obj.id,
                'totalUtgift': obj.totalUtgift,
                'totalInkomst': obj.totalInkomst
            }
            for obj in TheDay.objects.filter(date__lte=current_date , date__gte=week)
        ])
        return context

class EditInkomstView(UpdateView):
    model=DagligaInkomster
    fields='__all__'
    template_name="budget/edit-specific-inkomst.html"
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        id=self.kwargs['pk']
        the_form=DagligaInkomster.objects.get(id=id)
        this_date=the_form.the_day
        dags_inkomster=DagligaInkomster.objects.filter(the_day=this_date).order_by('klient')
        context['dags_inkomster']=dags_inkomster
        context["dags_utgifter"] = DagligaUtgifter.objects.filter(the_day=this_date).order_by('amount')
        return context

class EditUtgiftView(UpdateView):
    model=DagligaUtgifter
    fields='__all__'
    template_name="budget/edit-specific-utgift.html"
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        id=self.kwargs['pk']
        the_form=DagligaUtgifter.objects.get(id=id)
        this_date=the_form.the_day
        dags_inkomster=DagligaInkomster.objects.filter(the_day=this_date).order_by('klient')
        context['dags_inkomster']=dags_inkomster
        context["dags_utgifter"] = DagligaUtgifter.objects.filter(the_day=this_date).order_by('amount')
        return context



            

budget/templates/budget/idags-nya-inkomst-view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="" method="post">
 {% csrf_token %}
 <p>
   <label for="id_amount">Amount:</label>
   <input type="number" name="amount" value="0" required="" id="id_amount">
   
   
 </p>

 
 <p>
   <label for="id_klient">Klient:</label>
   <input name="klient" id="id_klient">
</input>
   
   
 </p>

 
 <p>
   <label for="id_kommentar">Kommentar:</label>
   <textarea name="kommentar" cols="40" rows="10" id="id_kommentar"></textarea>
   
   
</p>
  <button type="submit"></button>
   </form>
{% endblock content %}

budget/templates/budget/idags-nya-utgift-view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
   <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
   <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>

<!-- Content Row -->
<div class="row">



   <!-- Total spending-->
   <div class="col-xl-6 col-md-6 mb-4">
      <div class="card border-left-info shadow h-100 py-2 hover">
         <div class="card-body">
            <div class="row no-gutters align-items-center">
               <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Totala utgifter Idag
                  </div>
                  <div class="row no-gutters align-items-center">
                     <div class="col-auto">
                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ idag.totalUtgift }}</div>
                     </div>
                     <div class="col">
                        <div class="progress progress-sm mr-2">
                           <div class="progress-bar bg-info" role="progressbar" style="width: {{perut}}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-auto">
                  <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
               </div>
            </div>
         </div>
      </div>
   </div>

   <!-- Total income -->
   <div class="col-xl-6 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2 hover">
         <div class="card-body">
            <div class="row no-gutters align-items-center">
               <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                     Totala Inkomster Idag</div>
                  <div class="row no-gutters align-items-center">
                     <div class="col-auto">
                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ idag.totalInkomst }}</div>
                     </div>
                     <div class="col">
                        <div class="progress progress-sm mr-2">
                           <div class="progress-bar bg-info" role="progressbar" style="width: {{perin}}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-auto">
                  <i class="fas fa-comments fa-2x text-gray-300"></i>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<!-- Content Row -->

<div class="row">

   <!-- Area Chart -->
   <div class="col-xl-8 col-lg-7">
      <div class="card shadow mb-4 hover">
         <!-- Card Header - Dropdown -->
         <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
            <div class="dropdown no-arrow">
               <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
               </a>
               <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                  <div class="dropdown-header">Dropdown Header:</div>
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
               </div>
            </div>
         </div>
         <!-- Card Body -->
         <div class="card-body">
            <div class="chart-area">
               <div style="display: none" id="utdata" data-json="{{ utdata }}"></div>
               <div style="display: none" id="indata" data-json="{{ indata }}"></div>
               <div style="display: none" id="veckoutdata" data-json="{{ veckoutdata }}"></div>

               <canvas id="myAreaChart"></canvas>
            </div>
         </div>
      </div>
   </div>
   <!-- Pie Chart -->
   <div class="col-xl-4 col-lg-5">
      <div class="card shadow mb-4 hover">
         <!-- Card Header - Dropdown -->
         <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>

         </div>
         <!-- Card Body -->
         <div class="card-body">
            <div class="chart-pie pt-4 pb-2">
               <canvas id="myPieChart"></canvas>
            </div>
            <div class="mt-4 text-center small">
               <span class="mr-2">
                  <i class="fas fa-circle text-primary"></i> Inkomst
               </span>
               <span class="mr-2">
                  <i class="fas fa-circle text-success"></i> Utgift
               </span>

            </div>
         </div>
      </div>
   </div>
</div>

<!-- Content Row -->
<div class="row">

   <!-- Content Column -->
   <div class="col-lg-6 mb-4">
      <h1 class="h3 mb-4 text-gray-800 mx-auto text-center">Utgifter</h1>

      <!-- Project Card Example -->
      <div class="row">
         {% for item in utgifter %}
         <a class="col-xl-6 col-md-6 mb-4 " style="cursor:pointer;text-decoration: none;">
            <div class="card border-left-success shadow h-100 py-2 hover">
               <div class="card-body">
                  <div class="row no-gutters align-items-center">
                     <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                           {{item.name}}</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">sek {{item.amount}}</div>
                     </div>
                     <div class="col-auto">
                        <i class="fa fa-minus fa-2x text-gray-300"></i>
                     </div>
                  </div>
               </div>
            </div>
         </a>
         {% endfor %}

         <form class="col-xl-6 col-md-6 mb-4 " style="text-decoration: none;" method="post">
            {% csrf_token %}

            <div class="card border-left-success shadow h-100 py-2 hover">
               <div class="card-body">
                  <div class="row no-gutters align-items-center">
                     <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                           <input name="name" maxlength="100" required="" id="id_name" type="text" class="  form-control-sm col-6" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                           <input name="amount" value="0" required="" id="id_amount" type="number" class="form-control-sm col-6" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                           sek</div>
                     </div>
                     <button class="col-auto btn" type="submit">
                        <i class="fa fa-save fa-2x text-gray-300"></i>
                     </button>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>


   <!-- Inkomster -->
   <div class="col-lg-6 mb-4">
      <h1 class="h3 mb-4 text-gray-800 mx-auto text-center">Inkomster</h1>
      <div class="row">
         {% for item in inkomster %}
         <a class="col-xl-6 col-md-6 mb-4 " style="cursor:pointer;text-decoration: none;" data-bs-toggle="modal" data-bs-target="#ModalToggle">
            <div class="card border-left-primary shadow h-100 py-2 hover">
               <div class="card-body">
                  <div class="row no-gutters align-items-center">
                     <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                           {{item.name}}</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">sek {{item.amount}}</div>
                     </div>
                     <div class="col-auto">
                        <i class="fa fa-minus fa-2x text-gray-300"></i>
                     </div>
                  </div>
               </div>
            </div>
         </a>
         <!-- Modal -->
         <div class="modal fade" id="ModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
            <div class="modal-dialog">
               <div class="modal-content">
                  <div class="modal-header">
                     <h5 class="modal-title" id="exampleModalToggleLabel">{{item.name}}</h5>
                     <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                     {{item.kommentar}}
                  </div>
                  <div class="modal-footer">
                     <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Edit</button>
                  </div>
               </div>
            </div>
         </div>
         {% endfor %}
         <a class="col-xl-6 col-md-6 mb-4 " style="cursor:pointer;text-decoration: none;" href="{% url 'budget:idag-nya-in' %}">
            <div class="card border-left-primary shadow h-100 py-2 hover">
               <div class="card-body">
                  <div class="row no-gutters align-items-center">
                     <div class="col mr-2">

                        <div class="h5 mb-0 font-weight-bold text-gray-800">Lägg till en Inkomst</div>
                     </div>
                     <div class="col-auto">
                        <i class="fa fa-minus fa-2x text-gray-300"></i>
                     </div>
                  </div>
               </div>
            </div>
         </a>
      </div>
   </div>
</div>


<style>
   .hover {
      transition: box-shadow .3s;

   }

   .hover:hover {
      box-shadow: 2px 10px 20px rgba(0, 0, 0, .5) !important;

   }
</style>
<script>
   const ACTIVE_CLASS = "block--active";
   const TRANSITION_CLASS = "block--transition";
   const SVG_ICON = "mine"
   const getTransforms = (a, b) => {
      const scaleY = a.height / b.height;
      const scaleX = a.width / b.width;

      // dividing by 2 centers the transform since the origin
      // is centered not top left
      const translateX = a.left + a.width / 2 - (b.left + b.width / 2);
      const translateY = a.top + a.height / 2 - (b.top + b.height / 2);

      // nothing particularly clever here, just using the
      // translate amount to estimate a rotation direction/amount.
      // ends up feeling pretty natural to me.
      const rotate = translateX;

      return [
         `translateX(${translateX}px)`,
         `translateY(${translateY}px)`,
         `rotate(${rotate}deg)`,
         `scaleY(${scaleY})`,
         `scaleX(${scaleX})`
      ].join(" ");
   };

   const animate = (block, transforms, oldTransforms) => {
      block.style.transform = transforms;
      block.getBoundingClientRect(); // force redraw
      block.classList.add(TRANSITION_CLASS);
      block.style.transform = oldTransforms;
      block.addEventListener(
         "transitionend",
         () => {
            block.removeAttribute("style");
         }, {
            once: true
         }
      );
   };

   [...document.querySelectorAll(".block")].forEach(block => {
      const buttonForBlock = block.querySelector(".block-content__button");
      block.addEventListener("click", event => {
         if (
            block.classList.contains(ACTIVE_CLASS) &&
            event.target !== buttonForBlock
         ) {
            return;
         }

         block.classList.remove(TRANSITION_CLASS);
         const inactiveRect = block.getBoundingClientRect();
         const oldTransforms = block.style.transform;
         block.classList.toggle(ACTIVE_CLASS);
         const activeRect = block.getBoundingClientRect();
         const transforms = getTransforms(inactiveRect, activeRect);

         animate(block, transforms, oldTransforms);
      });
   });
</script>
{% endblock content %}